
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rpl1
 */
public class Laundry10 extends javax.swing.JFrame {

    /**
     * Creates new form Laundry10
     */
    public Laundry10() {
        initComponents();
    }
    public int Total_Harga;
    
    public void reset(){
        combo_jenis.setSelectedItem("pilih");
        txt_harga.setText("");
            txt_berat.setText("");
                txt_ttlHarga.setText("");
                    txt_bayar.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combo_jenis = new javax.swing.JComboBox<>();
        txt_harga = new javax.swing.JTextField();
        txt_berat = new javax.swing.JTextField();
        txt_ttlHarga = new javax.swing.JTextField();
        txt_bayar = new javax.swing.JTextField();
        btn_batal = new javax.swing.JButton();
        btn_transaksi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jenis Cuci");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LAUNDRY PAYMENT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Harga per KG");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Berat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Pembayaran");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pembayaran");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 90, -1));

        combo_jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Laundry", "Cuci Basah", "Cuci Kering", "Cuci Setrika" }));
        combo_jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_jenisActionPerformed(evt);
            }
        });
        jPanel1.add(combo_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 110, -1));

        txt_harga.setEditable(false);
        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 110, -1));

        txt_berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_beratActionPerformed(evt);
            }
        });
        txt_berat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_beratKeyReleased(evt);
            }
        });
        jPanel1.add(txt_berat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 110, -1));

        txt_ttlHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ttlHargaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_ttlHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 110, -1));

        txt_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bayarActionPerformed(evt);
            }
        });
        jPanel1.add(txt_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 110, -1));

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        btn_transaksi.setText("Bayar");
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 300, 440);

        setSize(new java.awt.Dimension(313, 424));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
     reset();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
if(txt_harga.getText().isEmpty()|| txt_berat.getText().isEmpty() ||
        txt_ttlHarga.getText().isEmpty() || txt_bayar.getText().isEmpty()){
    JOptionPane.showMessageDialog(null, "Data harus diisi");
}else{
    int bayar = Integer.parseInt(txt_bayar.getText());
    int kembalian = bayar - Total_Harga;
    if(kembalian <0){
       JOptionPane.showMessageDialog(null, "Uang Anda Kurang");
    } else {
        JOptionPane.showMessageDialog(null, "Kembalian Anda : \n"+kembalian);
    }
    reset();
}
    }//GEN-LAST:event_btn_transaksiActionPerformed

    private void combo_jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_jenisActionPerformed
      if(combo_jenis.getSelectedItem().equals("Pilih Jenis")){
          txt_harga.setText("0");
      }else  if(combo_jenis.getSelectedItem().equals("Cuci Basah")){
          txt_harga.setText("3000");
      }else  if(combo_jenis.getSelectedItem().equals("Cuci Kering")){
          txt_harga.setText("4000");
           }else  if(combo_jenis.getSelectedItem().equals("Cuci Setrika")){
          txt_harga.setText("5000");
        }
    }//GEN-LAST:event_combo_jenisActionPerformed

    private void txt_beratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_beratKeyReleased
if(txt_berat.getText().equals("")){
txt_ttlHarga.setText("0");
 }else{
 int harga = Integer.parseInt(txt_harga.getText());
  float berat = Float.parseFloat(txt_berat.getText());
  Total_Harga = (int) (harga*berat);
  txt_ttlHarga.setText(String.valueOf(Total_Harga));
}
    }//GEN-LAST:event_txt_beratKeyReleased

    private void txt_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bayarActionPerformed

    private void txt_ttlHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ttlHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ttlHargaActionPerformed

    private void txt_beratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_beratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_beratActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laundry10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laundry10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laundry10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laundry10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laundry10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.JComboBox<String> combo_jenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_berat;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_ttlHarga;
    // End of variables declaration//GEN-END:variables
}
